[build]
  command = "npm run build"  # Build komutunuz (örneğin, React veya Vue.js projeleri için)
  publish = "dist"            # Build çıktı dizini (build veya dist olabilir)

[[redirects]]
  from = "/index.html"
  to = "/*"
  status = 301
  force = true

[[redirects]]
    from = "/duyurular.html"
    to = "/*"
    status = 301
    force = true

[[redirects]]
    from = "akay.html"
    to = "/*"
    status = 301
    force = true

[[redirects]]
    from = "/duyuru1.html"
    to = "/*"
    status = 301
    force = "true"

[[redirects]]
    from = "parlamento.html"
    to = "/*"
    status = 301
    force = true

[[redirects]]
    from = "tarih.html"
    to = "/*"
    status = 301
    force = true